[INFO] [1742040162.303731954] [pose_subscriber]: Robot Position: x=0, y=0
[INFO] [1742040162.804087692] [pose_subscriber]: Robot Position: x=0, y=0
[INFO] [1742040165.569947431] [pose_subscriber]: Robot Position: x=0, y=-1
[INFO] [1742040167.113437469] [pose_subscriber]: Robot Position: x=1, y=-1
[INFO] [1742040167.999757778] [pose_subscriber]: Robot Position: x=1, y=-1
[INFO] [1742040170.814901445] [pose_subscriber]: Robot Position: x=1, y=-1
[INFO] [1742040173.736418560] [pose_subscriber]: Robot Position: x=2, y=-1
[INFO] [1742040176.512917654] [pose_subscriber]: Robot Position: x=2, y=-1
[INFO] [1742040179.537503477] [pose_subscriber]: Robot Position: x=3, y=-1
[INFO] [1742040180.785935694] [pose_subscriber]: Robot Position: x=3, y=-1
[INFO] [1742040183.277737968] [pose_subscriber]: Robot Position: x=3, y=-1
[INFO] [1742040185.763452310] [pose_subscriber]: Robot Position: x=4, y=0
[INFO] [1742040188.114374717] [pose_subscriber]: Robot Position: x=4, y=0
Traceback (most recent call last):
  File "/home/kyler/Documents/multiSLAM/channelUtils/pose_subscriber.py", line 50, in <module>
    rclpy.spin(node)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
    executor.spin_once()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 728, in _spin_once_impl
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 711, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 612, in _wait_for_ready_callbacks
    raise ExternalShutdownException()
rclpy.executors.ExternalShutdownException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kyler/Documents/multiSLAM/channelUtils/pose_subscriber.py", line 55, in <module>
    rclpy.shutdown()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 130, in shutdown
    _shutdown(context=context)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/utilities.py", line 58, in shutdown
    return context.shutdown()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/context.py", line 102, in shutdown
    self.__context.shutdown()
rclpy._rclpy_pybind11.RCLError: failed to shutdown: rcl_shutdown already called on the given context, at ./src/rcl/init.c:241
